config/routes.rb
Rails.application.routes.draw do
  devise_for :organizers, controllers: {
    sessions: 'organizers/sessions'
  }

  devise_scope :organizer do
    post 'organizers/guest_sign_in', to: 'organizers/sessions#new_guest'
  end

  devise_for :participants, controllers: {
    registrations: 'participants/registrations',
    sessions: 'participants/sessions'
  }

  devise_scope :participant do
    post 'participants/guest_sign_in', to: 'participants/sessions#new_guest'
    get '/contract' => 'participants/registrations#contract'
  end

  namespace :organizers do
    root 'homes#top'
    resources :participants, only: [:index, :show, :edit, :update] do
      resources :infos, only: [:show, :new, :create]
      post '/back' => 'infos#back'
      post '/confirm' => 'infos#confirm'
    end
    get '/infos' => 'infos#index'
    resources :events do
      resources :reservations, only: [:index, :destroy]
    end
  end

  scope module: :public do
    root 'homes#about'

    resources :events do
      resources :reservations, only: [:new, :create]
      resources :event_comments, only: [:create, :destroy]
    end
    
    resources :participants, only: [:show, :edit, :update] do
      resources :reservations, only: [:index, :destroy]
    end
    
    get '/participants/:id/withdrawal' => 'participants#withdrawal', as: 'participants_withdrawal'
    put '/participants/:id/unsubscribe' => 'participants#unsubscribe', as: 'participants_unsubscribe'
    get '/owabi' => 'homes#owabi'
    get '/thanks' => 'homes#thanks'
    get '/search' => 'searches#search'
  end

end

app/views/shared/_header_before_organizer.html.erb
<main>
  <div>
    <%= notice %>
    <%= alert %>
  </div>
  <header>
    <ul class="nav justify-content-end">
      <li class="nav-item mt-4">
        <%= link_to 'ゲストログイン（閲覧用）', organizers_guest_sign_in_path, method: :post, class: "nav-link" %>
      </li>
      <li class="nav-item mt-4">
        <%= link_to "ログイン", new_organizer_session_path, class: "nav-link" %>
      </li>
    </ul>
  </header>
  <%= yield %>
</main>

app/views/shared/_header_before_participant.html.erb
<main>
  <div>
    <%= notice %>
    <%= alert %>
  </div>
<header>
  <nav class="nav">
    <ul class="navber-left">
      <li class="nav-item-logo">
        <%= link_to root_path do %>
          <%= image_tag "logo2.png", class: "nav-link-logo"%>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-right">
      <li class="nav-item">
        <%= link_to 'ゲストログイン（閲覧用）', participants_guest_sign_in_path, method: :post, class: "nav-link" %>
      </li>
    </ul>
  </nav>
  <div id="sp-menu">
      <h2>目次<i class="fas fa-coffee"></i></h2>
      <ul>
        <li><%= link_to "虫めがね村について", root_path, class: "fas fa-search" %></li>
        <li><%= link_to "イベント一覧", events_path, class: "fas fa-book-open" %></li>
        <li><%= link_to "新規会員登録", new_participant_registration_path, class: "far fa-user" %></li>
        <li><%= link_to "ログイン", new_participant_session_path, class: "fas fa-sign-in-alt" %></li>
      </ul>
    </div>

    <div id="hm-icon">
      <a id="menu-trigger" href="">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>

    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>

</header>
  <%= yield %>
</main>

app/views/shared/_header_organizer.html.erb
<main>
  <div>
    <%= notice %>
    <%= alert %>
  </div>
  <header>
    <div id="sp-menu">
        <h2>目次</h2>
        <ul>
          <li><%= link_to "直近のイベント一覧", organizers_root_path %></li>
          <li><%= link_to "イベント一覧", organizers_events_path %></li>
          <li><%= link_to "イベント投稿", new_organizers_event_path %></li>
          <li><%= link_to "会員一覧", organizers_participants_path %></li>
          <li><%= link_to "メール送信履歴一覧", organizers_infos_path %></li>
          <li><%= link_to "ログアウト", destroy_organizer_session_path, method: :delete %></li>
        </ul>
      </div>

      <div id="hm-icon">
        <a id="menu-trigger" href="">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>

      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
  </header>
  <%= yield %>
</main>

app/views/shared/_header_participant.html.erb
<main>
  <div>
    <%= notice %>
    <%= alert %>
  </div>
  <header>
    <nav class="nav">
      <ul class="navber-left">
        <li class="nav-item-logo">
          <%= link_to root_path do %>
            <%= image_tag "logo2.png", class: "nav-link-logo"%>
          <% end %>
        </li>
      </ul>
    </nav>
    <div id="sp-menu">
        <h2>目次<i class="fas fa-coffee"></i></h2>
        <ul>
          <li><%= link_to "イベント一覧", events_path, class: "far fa-calendar-alt" %></li>
          <li><%= link_to "マイページ", participant_path(current_participant), class: "fas fa-user-circle" %></li>
          <li><%= link_to "参加イベント", participant_reservations_path(current_participant), class: "far fa-comments" %></li>
          <li><%= link_to "ログアウト", destroy_participant_session_path, method: :delete, class: "fas fa-sign-out-alt" %></li>
        </ul>
      </div>

      <div id="hm-icon">
        <a id="menu-trigger" href="">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>

      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
  </header>
  <%= yield %>
</main>