config/routes.rb
Rails.application.routes.draw do
  devise_for :organizers, controllers: {
    sessions: 'organizers/sessions'
  }

  devise_scope :organizer do
    post 'organizers/guest_sign_in', to: 'organizers/sessions#new_guest'
  end

  devise_for :participants, controllers: {
    registrations: 'participants/registrations',
    sessions: 'participants/sessions'
  }

  devise_scope :participant do
    post 'participants/guest_sign_in', to: 'participants/sessions#new_guest'
    get '/contract' => 'participants/registrations#contract'
  end

  namespace :organizers do
    root 'homes#top'
    resources :participants, only: [:index, :show, :edit, :update] do
      resources :infos, only: [:show, :new, :create]
      post '/back' => 'infos#back'
      post '/confirm' => 'infos#confirm'
    end
    get '/infos' => 'infos#index'
    resources :events do
      resources :reservations, only: [:index, :destroy]
    end
  end

  scope module: :public do
    root 'homes#about'

    resources :events do
      resources :reservations, only: [:new, :create]
      resources :event_comments, only: [:create, :destroy]
    end
    
    resources :participants, only: [:show, :edit, :update] do
      resources :reservations, only: [:index, :destroy]
    end
    
    get '/participants/:id/withdrawal' => 'participants#withdrawal', as: 'participants_withdrawal'
    put '/participants/:id/unsubscribe' => 'participants#unsubscribe', as: 'participants_unsubscribe'
    get '/owabi' => 'homes#owabi'
    get '/thanks' => 'homes#thanks'
    get '/search' => 'searches#search'
  end

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :reservations, dependent: :destroy
  has_many :reserving_participants, through: :reservation, source: :participant
  has_many :event_comments, dependent: :destroy
  
  accepts_nested_attributes_for :reservations, allow_destroy: true
  
  attachment :image

  def reserved_by?(participant)
    reservations.where(participant_id: participant.id).exists?
  end

  validates :date_and_time, :event_name, :content, :number_of_reservations, presence: true
  validates :number_of_reservations, numericality: { greater_than_or_equal_to: 1 }
  validates :is_active, inclusion: {in: [true, false]}

  validate :date_cannot_be_in_the_past
  def date_cannot_be_in_the_past
    if date_and_time.present? && date_and_time < DateTime.now
      errors.add(:date_and_time, "この日付は使用できません")
    end
  end

  scope :search, -> (search_params) do      #scopeでsearchメソッドを定義。(search_params)は引数
    return if search_params.blank?      #検索フォームに値がなければ以下の手順は行わない

    event_name_like(search_params[:event_name])
      .date_and_time_from(search_params[:date_and_time_from])#下記で定義しているscopeメソッドの呼び出し。「.」で繋げている
      .date_and_time_to(search_params[:date_and_time_to])
  end

  scope :event_name_like, -> (event_name) { where('event_name LIKE ?', "%#{event_name}%") if event_name.present? }  #scopeを定義
  scope :date_and_time_from, -> (from) { where('? <= date_and_time', from) if from.present? }
  scope :date_and_time_to, -> (to) { where('date_and_time < ?', (Date.parse(to)+1).to_s) if to.present? }
  # ('? <= date_and_time', from)の場合は日付の取得が◯月◯日の０時０分以下になってしまう。その為、< 実際に検索した日付+1日未満のものを探すようにする。
  # 入力された値(to)は文字列になっている為、日付に変換する。parseにて(to)を変換＋１して.to_sで文字列に変換する
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: 'guest@organizer.com') do |organizer|
      organizer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/organizers/confirmations_controller.rb
# frozen_string_literal: true

class Organizers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/organizers/events_controller.rb
class Organizers::EventsController < ApplicationController
  before_action :authenticate_organizer!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.order("created_at DESC").page(params[:page]).per(5)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
  if @event.save
    redirect_to organizers_event_path(@event.id), notice: "イベントを登録しました"
  else
    render :new
  end
  end


  def edit
  end

  def update
  if@event.update(event_params)
    redirect_to organizers_event_path(@event.id)
  else
    flash[:notice] = "イベントの更新ができませんでした"
    redirect_back(fallback_location: root_path)
  end
  end

  def destroy
    @event.destroy
    redirect_to organizers_events_path, notice: "イベントを削除しました"
  end

  private
  def event_params
    params.require(:event).permit(:participant_id, :date_and_time, :event_name, :image, :is_active, :content, :number_of_reservations)
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/organizers/homes_controller.rb
class Organizers::HomesController < ApplicationController
  before_action :authenticate_organizer!

  def top
    @events = Event.order("date_and_time").where('date_and_time >= ?', DateTime.now).page(params[:page]).per(5)
  end

  private
  def event_params
    params.require(:event).permit(:participant_id, :date_and_time, :event_name, :image, :is_active, :content, :number_of_reservations)
  end

end

app/controllers/organizers/infos_controller.rb
class Organizers::InfosController < ApplicationController
  before_action :authenticate_organizer!

  def index
    @infos = Info.order(id: "DESC").page(params[:page]).per(15)
  end

  def new
    @info = Info.new
    @participant = Participant.find(params[:participant_id])
  end

  def show
    @info = Info.find(params[:id])
    @participant = Participant.find(params[:participant_id])
  end

  def confirm
    @info = Info.new(info_params)
    @info.participant_id = params[:participant_id]
    session[:info] = @info
    if @info.invalid?
      @participant = Participant.find(params[:participant_id])
      render :new
    end
  end

  def back
    @info = Info.new(session[:info])
    @info.participant_id = params[:participant_id]
    session.delete(:info)
    @participant = Participant.find(params[:participant_id])
		render :new
  end

  def create
    @info = Info.new(info_params)
    @participant = Participant.find(params[:participant_id])
    @info.participant_id = @participant.id
    if @info.save
      InfoMailer.info_mail(@info, @participant).deliver_now
      redirect_to organizers_participant_info_path(@participant, @info)
    else
      render :confirm
    end
  end

  private
  def info_params
    params.require(:info).permit(:message)
  end

end

app/controllers/organizers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Organizers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/organizers/participants_controller.rb
class Organizers::ParticipantsController < ApplicationController
  before_action :authenticate_organizer!
  before_action :guest_organizer, only: [:edit, :update]
  before_action :set_participant, only: [:show, :edit, :update]

  def guest_organizer
    @organizer = Organizer.find_by(email: 'guest@organizer.com')
    if @organizer == current_organizer
      flash[:notice] = 'ゲストユーザーは編集が出来ません'
      redirect_to organizers_root_path
    end
  end

  def index
    @participants = Participant.all
  end

  def show
  end

  def edit
  end

  def update
  if@participant.update(participant_params)
    redirect_to organizers_participant_path(@participant.id), notice: "会員情報の更新ができました"
  else
    render :edit, notice: "会員情報が保存できませんでした"
  end
  end

  private
  def participant_params
    params.require(:participant).permit(:nickname, :telephone_number, :is_deleted, :email)
  end

  def set_participant
    @participant = Participant.find(params[:id])
  end

end

app/controllers/organizers/passwords_controller.rb
# frozen_string_literal: true

class Organizers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/organizers/registrations_controller.rb
# frozen_string_literal: true

class Organizers::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_organizer!
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/organizers/reservations_controller.rb
class Organizers::ReservationsController < ApplicationController
  before_action :authenticate_organizer!

  def index
    @event = Event.find(params[:event_id])
    @reservations = @event.reservations.all
  end

  def destroy
    @event = Event.where(id: params[:event_id]).where(participant_id: params[:participant_id])
    @participant = Participant.find_by(id: params[:id])
    @reservation = @participant.reservations.find_by(event_id: params[:event_id])
    @reservation.destroy
    redirect_to organizers_event_reservations_path, notice: "予約を削除しました"
  end

  private

  def reservation_params
    params.permit(:participant_id, :event_id, :attendance_status)
  end

end

app/controllers/organizers/sessions_controller.rb
# frozen_string_literal: true

class Organizers::SessionsController < Devise::SessionsController
  def new_guest
    organizer = Organizer.guest
    sign_in organizer
    redirect_to organizers_root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  private
  def after_sign_in_path_for(resource)
    organizers_root_path
  end

  def after_sign_out_path_for(resource)
    new_organizer_session_path
  end
end

app/controllers/organizers/unlocks_controller.rb
# frozen_string_literal: true

class Organizers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/organizers/events_helper.rb
module Organizers::EventsHelper
end

app/helpers/organizers/homes_helper.rb
module Organizers::HomesHelper
end

app/helpers/organizers/infos_helper.rb
module Organizers::InfosHelper
end

app/helpers/organizers/participants_helper.rb
module Organizers::ParticipantsHelper
end

app/helpers/organizers/reservations_helper.rb
module Organizers::ReservationsHelper
end

app/views/organizers/events/edit.html.erb
<div class="container mt-4">
  <div class="col-md-5 col-md-offset-4">
    <h3>イベント情報編集</h3>
	<%= form_with model: @event, url: organizers_event_path(@event.id), local: true do |f| %>

		<!-- イベント画像 -->
		<div class="form-group">
			<%= attachment_image_tag @event, :image, :fill, 100, 100 %>
			<%= f.attachment_field :image, placeholder: "Image" %>
		</div>

		<!-- イベント名 -->
		<div class="form-group">
			<%= f.label :event_name, "イベント名"%><br>
			<%= f.text_field :event_name, :size=>"40", autofocus: true %>
		</div>

		<!-- イベント内容説明 -->
		<div class="form-group">
			<%= f.label :content, "イベント内容"%><br>
			<%= f.text_area :content, :size=>"40", autofocus: true%>
		</div>

		<!-- 　開催日時　 -->
		<div class="form-group">
			<%= f.label :date_and_time, "日時(過去の日時では登録できません)"%><br>
			<%= f.datetime_select :date_and_time,{:minute_step => 30}, autofocus: true%>
		</div>

　　　　　　　<!-- 参加人数  -->
		<div class="form-group">
			<%= f.label :number_of_reservations, "参加上限人数(半角で入力してください)"%><br>
			<%= f.text_field :number_of_reservations, autofocus: true %>
		</div>

		<!-- 開催ステータス -->
		<div class="form-group">
			<%= f.label :is_active, "開催状況"%><br>
			<%= f.select :is_active, {'開催前': true, '終了': false}, { class: 'form-control' , required: true } %>
		</div>

		<%= f.submit '変更を登録する', data: { confirm: "この内容で変更しますか？" }, class:"btn btn-info btn-md" %>

	<% end %>
  </div>
</div>

app/views/organizers/events/index.html.erb
<div class="container mt-4">
  <h4>作成イベント一覧(作成順)</h4>
  <table class="table mt-5">
    <% if @events.present? %>
      <thead>
        <tr>
          <th>ID</th>
          <th>イベント画像</th>
          <th class="col-md-2">イベント名</th>
          <th class="col-md-4">内容</th>
          <th class="col-md-1">日時</th>
          <th class="col-md-1">受付人数</th>
          <th class="col-md-1">開催状況</th>
          <th class="col-md-1">予約人数/予約上限</th>
          <th class="col-md-1"></th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.id %></td>
            <td><%= attachment_image_tag event, :image , fallback:"no_image.jpg", size:'100x100'%></td>
            <td><%= link_to event.event_name, organizers_event_path(event.id)%></td>
            <td style="word-wrap:break-word;"><%= event.content %></td>
            <td><%= l event.date_and_time %></td>
            <td>　<%= event.number_of_reservations %>人</td>
            <% if !(event.is_active == false) && event.date_and_time >= DateTime.now %>
              <td>　開催前</td>
            <% else %>
              <td>　終了</td>
            <% end %>
            <td>　　　<%= "#{event.reservations.count} " %>/<%= event.number_of_reservations %></td>
            <td><%= link_to "予約者一覧",organizers_event_reservations_path(event,@reservation)%></td>
          </tr>
        <% end %>
      <tbody>
    <% else %>
      <td>新しいイベントを開催しましょう☺︎</td>
    <% end %>
  </table>
  <div class="text-center">
    <%= paginate @events %>
  </div>
</div>

app/views/organizers/events/new.html.erb
<div class="container mt-4">
  <div class="col-md-5 col-md-offset-4">
    <h3>新規イベント投稿</h3>
	
		<%= form_with model: @event, url: organizers_events_path, method: :post, local: true do |f| %>
		  <%= render 'layouts/error_messages', model: f.object %>
      <!-- イベント画像 -->
      <div class="form-group">
				<%= attachment_image_tag @event, :image, :fill, 100, 100 %>
				<%= f.attachment_field :image, placeholder: "Image" %>
			</div>

			<!-- イベント名 -->
			<div class="form-group">
				<%= f.label :event_name, "イベント名"%><br>
				<%= f.text_field :event_name, :size=>"40", autofocus: true %>
			</div>

			<!-- イベント内容説明 -->
			<div class="form-group">
				<%= f.label :content, "イベント内容"%><br>
				<%= f.text_area :content, :size=>"40", autofocus: true%>
			</div>

			<!-- 　開催日時　 -->
			<div class="form-group">
				<%= f.label :date_and_time, "日時(過去の日時では登録できません)"%><br>
				<%= f.datetime_select :date_and_time,{:minute_step => 30}, autofocus: true%>
			</div>

			<!-- 参加人数  -->
      <div class="form-group">
				<%= f.label :number_of_reservations, "参加上限人数(半角で入力してください)"%><br>
				<%= f.text_field :number_of_reservations, autofocus: true %>
			</div>
			
			<%= f.submit '新規登録',class:"btn btn-info btn-md" %>
		<% end %>
  
  </div>
</div>

app/views/organizers/events/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-3 mt-4">
      <%= attachment_image_tag @event, :image , fallback:"no_image.jpg", size:'200x200'%>
    </div>
    
    <div class="col-md-9">
      <h3>イベント詳細</h3>
        <div class="show-text">
            <p>イベント名：<%= @event.event_name %></p>
            <p>イベント内容：<%= @event.content %></p>
            <p>開催日時：<%= l @event.date_and_time %></p>
            <p>参加上限人数：<%= @event.number_of_reservations %>人</p>
            <p>開催状況：
              <% if !(@event.is_active == false) && @event.date_and_time >= DateTime.now %>
                <td>開催前</td>
              <% else %>
                <td>終了</td>
              <% end %>
            </p>
            <p>イベント内容最終更新日時：<%= l @event.updated_at %></p>
        </div>
    
        <%= link_to '編集する', edit_organizers_event_path, class: "btn btn-info btn-md mt-4" %>
        <%= link_to '削除する', organizers_event_path, method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }, class: "btn btn-danger btn-md mt-4" %>
    </div>
  </div>
</div>