config/routes.rb
Rails.application.routes.draw do
  devise_for :organizers, controllers: {
    sessions: 'organizers/sessions'
  }

  devise_scope :organizer do
    post 'organizers/guest_sign_in', to: 'organizers/sessions#new_guest'
  end

  devise_for :participants, controllers: {
    registrations: 'participants/registrations',
    sessions: 'participants/sessions'
  }

  devise_scope :participant do
    post 'participants/guest_sign_in', to: 'participants/sessions#new_guest'
    get '/contract' => 'participants/registrations#contract'
  end

  namespace :organizers do
    root 'homes#top'
    resources :participants, only: [:index, :show, :edit, :update] do
      resources :infos, only: [:show, :new, :create]
      post '/back' => 'infos#back'
      post '/confirm' => 'infos#confirm'
    end
    get '/infos' => 'infos#index'
    resources :events do
      resources :reservations, only: [:index, :destroy]
    end
  end

  scope module: :public do
    root 'homes#about'

    resources :events do
      resources :reservations, only: [:new, :create]
      resources :event_comments, only: [:create, :destroy]
    end
    
    resources :participants, only: [:show, :edit, :update] do
      resources :reservations, only: [:index, :destroy]
    end
    
    get '/participants/:id/withdrawal' => 'participants#withdrawal', as: 'participants_withdrawal'
    put '/participants/:id/unsubscribe' => 'participants#unsubscribe', as: 'participants_unsubscribe'
    get '/owabi' => 'homes#owabi'
    get '/thanks' => 'homes#thanks'
    get '/search' => 'searches#search'
  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MushimeganeMura</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-XQGB5S74JN"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-XQGB5S74JN');
    </script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if organizer_signed_in? %>
      <%= render "shared/header_organizer" %>
    <% elsif /\/organizers/ =~ request.fullpath %>
      <%= render "shared/header_before_organizer" %>
    <% elsif participant_signed_in? %>
      <%= render "shared/header_participant" %>
    <% else %>
      <%= render "shared/header_before_participant" %>
    <% end %>
      <footer class="fixed-bottom"></footer>
  </body>
</html>